[package]
name = "iflow-cli-action"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
serde_json = "1.0"
dirs = "5.0"
tempfile = "3.0"

[[bin]]
name = "iflow-cli-action"
path = "src/main.rs"