# Example: Using Extra Arguments with iFlow CLI Action
name: iFlow with Extra Arguments

on:
  workflow_dispatch:

jobs:
  # Example 1: Basic extra arguments
  basic_extra_args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run with verbose output
        uses: iflow-ai/iflow-cli-action@v2.0.0
        with:
          prompt: "Analyze this codebase"
          api_key: ${{ secrets.IFLOW_API_KEY }}
          debug: "true"

  # Example 2: Multiple flags
  multiple_flags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run with multiple custom flags
        uses: iflow-ai/iflow-cli-action@v2.0.0
        with:
          prompt: "Generate unit tests for the main functions"
          api_key: ${{ secrets.IFLOW_API_KEY }}
          debug: "true"



