name: iFlow with MCP

on:
  workflow_run:
    workflows: ["Build and Deploy Homepage"]
    types:
      - completed
  # Allow manual trigger
  workflow_dispatch:
  # Also run on pushes to main branch
  push:
  #   branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: iFlow CLI with MCP
        uses: ./
        with:
          prompt: "use @deepwiki to search how to use Skynet to build a game"
          api_key: ${{ secrets.IFLOW_API_KEY }}
          settings_json: |
            {
                "selectedAuthType": "iflow",
                "apiKey": "${{ secrets.IFLOW_API_KEY }}",
                "baseUrl": "https://apis.iflow.cn/v1",
                "modelName": "Qwen3-Coder",
                "searchApiKey": "${{ secrets.IFLOW_API_KEY }}",
                "mcpServers": {
                    "deepwiki": {
                        "command": "npx",
                        "args": ["-y", "mcp-deepwiki@latest"]
                    }
                }
            }
          model: "Qwen3-Coder"
          timeout: "3600"
          extra_args: "--debug"
          iflow_version: "0.2.11"
