name: '🚀 iFlow CLI PR Review Killer'

on:
  issue_comment:
    types:
      - 'created'

concurrency:
  group: '${{ github.workflow }}-${{ github.event.issue.number }}'
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

permissions:
  contents: 'write'
  issues: 'write'
  pull-requests: 'write'

jobs:
  modify-code:
    if: |-
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      (
        contains(github.event.comment.body, '@iflow-cli /review-killer') ||
        contains(github.event.comment.body, '@iFlow-CLI /review-killer') ||
        contains(github.event.comment.body, '@IFLOW-CLI /review-killer') ||
        contains(github.event.comment.body, '@IFlow-CLI /review-killer')
      ) &&
      contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    timeout-minutes: 30
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout PR branch
        uses: xt0rted/pull-request-comment-branch@v3.0.0
        id: checkout_pr
        
      - name: Extract instructions from comment
        id: extract
        run: |
          COMMENT="${{ github.event.comment.body }}"
          # Extract everything after "@iflow-cli /review-killer " (case insensitive)
          # First check if the pattern exists, then extract
          if echo "$COMMENT" | grep -qiE '@iflow-cli[[:space:]]+/review-killer'; then
            INSTRUCTIONS=$(echo "$COMMENT" | sed -E 's/.*@[iI][fF][lL][oO][wW]-[cC][lL][iI][[:space:]]+\/[rR][eE][vV][iI][eE][wW]-[kK][iI][lL][lL][eE][rR][[:space:]]*(.*)/\1/' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          else
            INSTRUCTIONS=""
          fi
          echo "instructions=$INSTRUCTIONS" >> $GITHUB_OUTPUT

      - name: 'Run iFlow CLI Implementation'
        uses: ./
        id: 'iflow_cli_implementation'
        with:
          api_key: ${{ secrets.IFLOW_API_KEY }}
          timeout: "1800"
          extra_args: "--debug"
          settings_json: |
            {
                "selectedAuthType": "iflow",
                "apiKey": "${{ secrets.IFLOW_API_KEY }}",
                "baseUrl": "https://apis.iflow.cn/v1",
                "modelName": "Qwen3-Coder",
                "searchApiKey": "${{ secrets.IFLOW_API_KEY }}",
                "mcpServers": {
                  "github": {
                  "command": "github-mcp-server",
                  "args": [
                    "stdio"
                  ],
                  "includeTools": [
                    "add_issue_comment"
                  ],
                    "env": {
                      "GITHUB_PERSONAL_ACCESS_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
                    }
                  }
                }
            }
          prompt: |
            ## Role

            You are a PR review assistant. Your task is to modify code based on
            review comments. Follow these steps:

            1. Analyze the PR review comment provided in the environment
               variables.
            2. Extract the modification instructions from the comment: "${{ steps.extract.outputs.instructions }}"
            3. Implement the requested changes by creating or modifying files as
               needed.
            4. Ensure all changes are complete and correct according to the review
               requirements.
            5. Focus only on implementing the current review comment.

            ## Guidelines

            - Make all necessary code changes to address the review comment
            - Ensure new code follows existing project conventions
            - Add or modify tests if applicable
            - Reference all shell variables as "${VAR}" (with quotes and braces)
            
            ## Committing Changes
            
            After implementing the changes:
            1. Stage all modified files
            2. Commit the changes with a descriptive message
            3. Push the changes to the ${{ steps.checkout_pr.outputs.head_ref }} branch

            **NEVER commit directly to the `main` branch.**
            **NEVER force push**


      # - name: Commit and push changes
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #     git add .
      #     git commit -m "Apply code modifications from PR review comment" || exit 0
      #     git push origin ${{ steps.checkout_pr.outputs.head_ref }}