name: build ci image and push image to ghcr.io

on:
  workflow_dispatch:
#   push:
#     branches:
#       - "main"

permissions:
    contents: read
    packages: write

jobs:
  build-ci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6.18.0
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository_owner }}/iflow-cli-action:latest
            ghcr.io/${{ github.repository_owner }}/iflow-cli-action:latest
