name: Run unittests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-hrp:
    strategy:
      matrix:
        go-version:
          - 1.24
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic -race ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          name: iflow-cli-action # User defined upload name. Visible in Codecov UI
          token: ${{ secrets.CODECOV_TOKEN }} # Repository upload token
          flags: unittests # Flag upload to group coverage metrics
          fail_ci_if_error: true # Specify whether or not CI build should fail if Codecov runs into an error during upload
          verbose: true
